#pragma once
#define SCREENMATE_MONITORS 64
#define SCREENMATE_AUDIO_EVENTS 128
#define SCREENMATE_SHARED_BYTES 262144
#define SCREENMATE_SHARED_MAGIC 0x534d5031
typedef struct {
    LONG magic,count,primary,ticks;
    LONG tickets[SCREENMATE_MONITORS];
    LONG rootCalls[SCREENMATE_MONITORS];
    LONG admitted[SCREENMATE_MONITORS];
    LONG audioWrite[SCREENMATE_MONITORS];
    LONG audioRead[SCREENMATE_MONITORS];
    LONG audioForwarded[SCREENMATE_MONITORS];
    LONG audioPlayed[SCREENMATE_MONITORS];
    LONG audioErrors;
    DWORD audio[SCREENMATE_MONITORS][SCREENMATE_AUDIO_EVENTS];
    LONG actionLock;
    LONG actionOwner[9];
    LONG actionStarts[9];
    BYTE audioProperties[SCREENMATE_MONITORS][SCREENMATE_AUDIO_EVENTS][10];
    LONG actionPending[9];
    LONG requestWrite[SCREENMATE_MONITORS];
    LONG requestRead[SCREENMATE_MONITORS];
    DWORD requests[SCREENMATE_MONITORS][SCREENMATE_AUDIO_EVENTS];
} SCREENMATE_SHARED;
